version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog
    container_name: blog-mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
  redis:
    image: redis:6.2
    restart: always
    volumes:
      - redis-data:/data
    container_name: blog-redis
    ports:
      - "16379:6379"
volumes:
  db-data:
  redis-data: